apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::897729141306:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-6mBP8kpSWr3o
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::897729141306:user/suresh 
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-30T16:02:26Z"
  name: aws-auth
  namespace: kube-system
  uid: 613843d2-f6ad-4c4b-b058-30cb22bc7067